services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ThisIsAComplicatePassWord}
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql/test.sql:/docker-entrypoint-initdb.d/test.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge